/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package software.amazon.awscdk.dsl.examples

import software.amazon.awscdk.dsl.app
import software.amazon.awscdk.dsl.services.lambda.*
import software.amazon.awscdk.dsl.stack
import software.amazon.awscdk.services.lambda.Code
import software.amazon.awscdk.services.lambda.Runtime.NODE_J_S810


fun main() {

    app {
        stack("myStackId") {
            function("myFunctionId", functionProps {
                functionName = "myFunction"
                runtime = NODE_J_S810
                memorySize = 128
                handler = "index.handler"
                code = Code.inline("""
                    exports.handler = function(event, context, callback) {
                        callback(null, "Hello, World!");
                    }
                """.trimIndent())
            })
        }
    }.run()
}
